#!/bin/bash

echo "=== 시놀로지 Docker 환경 확인 스크립트 ==="
echo ""
echo "SSH 연결 후 다음 명령어들을 실행하세요:"
echo ""
echo "# 1. Docker 버전 확인"
echo "docker --version"
echo "docker-compose --version"
echo ""
echo "# 2. 현재 실행 중인 컨테이너"
echo "docker ps"
echo ""
echo "# 3. Docker 이미지 목록"
echo "docker images"
echo ""
echo "# 4. 볼륨 확인 및 디렉토리 생성"
echo "ls -la /volume1/"
echo "sudo mkdir -p /volume1/docker/insightforge"
echo "sudo chown -R btf_admin:users /volume1/docker/insightforge"
echo ""
echo "# 5. 디스크 공간 확인"
echo "df -h /volume1"
echo ""
echo "# 6. 네트워크 확인"
echo "ip addr show"
echo ""

