#!/bin/bash

echo "=== 시놀로지 NAS 설정 가이드 ==="
echo ""
echo "시놀로지 정보:"
echo "  주소: http://192.168.219.2:5000"
echo "  ID: btf_admin"
echo "  PW: Ks&js140405"
echo ""
echo "============================================"
echo "1단계: SSH 접속 테스트"
echo "============================================"
echo ""
echo "다음 명령어를 실행하세요:"
echo "  ssh btf_admin@192.168.219.2"
echo ""
echo "비밀번호 입력: Ks&js140405"
echo ""
echo "연결 후 확인할 명령어:"
echo "  1. uname -a                    # 시스템 정보"
echo "  2. cat /etc/synoinfo.conf | grep model  # 모델명"
echo "  3. docker --version            # Docker 설치 확인"
echo "  4. df -h                       # 디스크 공간"
echo "  5. ls -la /volume1/            # 볼륨 목록"
echo ""
