#!/bin/bash

echo "==================================="
echo "🚀 Synology NewsAnalyzer 시작"
echo "==================================="
echo ""
echo "📍 연결 정보:"
echo "  IP: 192.168.219.2:5000"
echo "  계정: btf_admin"
echo "  비밀번호: D9BXMAZIaIbwtQW"
echo "  sudo 비밀번호: 1162916"
echo ""
echo "🔧 실행할 명령어:"
echo ""
echo "1️⃣ SSH 접속 (복사하여 실행):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ssh btf_admin@192.168.219.2"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣ 디렉토리 이동 (SSH 접속 후):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd /volume1/BTF-Tech/newsanalyzer-temp/NewsAnalyzer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣ Docker 시작:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "sudo docker compose up -d newsanalyzer-historical"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4️⃣ 로그 확인:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "sudo docker compose logs -f newsanalyzer-historical"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 성공 시 로그에서 보이는 메시지:"
echo "  === 역사적 뉴스 수집 시작 ==="
echo "  📍 현재 Phase: 1"
echo "  📅 수집 날짜: 2020-01-01"
echo "  📊 대상: 1,409명"
echo ""
echo "==================================="

